ServiceName = "envs-ingress-test2"
Name = "envs-ingress-test2"
Description = "Hello Koala!"
Owners = ["nadaverell@gmail.com"]
ServerFramework = "go-server"
ServerMain = ""
ArtifactRepository = "me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo"
Domain = "cluster.koalaops.com"
Port = 8080

[Repo]
  Name = "envs-ingress-test2"
  GitUser = "koala-sandbox"
  URL = "https://github.com/koala-sandbox/envs-ingress-test2"
  Token = ""

[OpenAPIConfig]
  SpecPath = ""
  CodegenTool = ""

[[Environments]]
  Name = "dev"
  Namespace = "dev"
  Cluster = "koala-demo-cluster"
  IngressEnabled = true
  IngressHost = ""
  [Environments.EnvDeploymentConfig]
    AutoDeploy = true

[[Environments]]
  Name = "prod"
  Namespace = "prod"
  Cluster = "koala-demo-cluster"
  IngressEnabled = true
  IngressHost = ""
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false

[[Environments]]
  Name = "staging"
  Namespace = "staging"
  Cluster = "koala-demo-cluster"
  IngressEnabled = false
  IngressHost = ""
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false

[SSLConfig]
  CertName = ""
  Issuer = ""
  IssuerContactEmail = ""

[Tracing]
  Backend = ""
  URL = ""

[Profiling]
  Tool = ""
